const textBlock: TextBlock = {
    id: 'id1', 
    x1: 0,
    y1: 0,
    x2: 1,
    y2: 1,
    type: 'text',
    chars: [{ 
        value: 'q',
        fontSize: 14,
        fontFamily: 'Comic Sans MS',
        color: 'black',
        bold: false,
        underlined: false,
        opacity: 100,

    }],
    alignment: Alignment.Without,
    angelRotate: 30,
}

const circle: Circle  =  {
    id: 'id2',
    type: 'graphics',
    color: 'red',
    borderThickness: 2,
    colorBorder: 'grey',
    text: {
        id: 'id2', 
        x1: 0,
        y1: 0,
        x2: 1,
        y2: 1,
        type: 'text',
        chars: [],
        alignment: Alignment.Without,
        angelRotate: 0,
    },
    opacity: 100,
    angelRotate: 0,
    radius: 5,
    xCoordCentre: 1,
    yCoordCentre: 1,
}

const rectangle: Rectangle = {
    id: 'id3',
    type: 'graphics',
    color: 'green',
    borderThickness: 2,
    colorBorder: 'grey',
    text: {
        id: 'id2', 
        xCoord: 1,
        yCoord: 1,
        type: 'text',
        chars: [],
        alignment: Alignment.Without,
        angelRotate: 0,
    },
    opacity: 100,
    angelRotate: 0,
    xCoord: 2,
    yCOord: 2,
    width: 2,
    height: 3,
}

type Triangle = GraphicObject & {
    id: 'id3',
    type: 'graphics',
    color: 'green',
    borderThickness: 2,
    colorBorder: 'grey',
    text: {
        id: 'id2', 
        xCoord: 1,
        yCoord: 1,
        type: 'text',
        chars: [],
        alignment: Alignment.Without,
        angelRotate: 0,
    },
    opacity: 100,
    angelRotate: 0,
    xFirstCoord: number,
    yFitrstCoord: number,
    xSecondCoord: number,
    ySecondCoord: number,
    xThirdCoord: number,
    yThirdCoord: number,
}
